CREATE TABLE chat_channel (
  chat_channel_name VARCHAR(255) NOT NULL,
  PRIMARY KEY (chat_channel_name)
);

CREATE TABLE chat_group (
  chat_group_id BIGINT generated BY DEFAULT AS IDENTITY (START WITH 1),
  PRIMARY KEY (chat_group_id)
);

CREATE TABLE chat_server (
  chat_server_id        BIGINT generated BY DEFAULT AS IDENTITY (START WITH 1),
  chat_server_host_name VARCHAR(255),
  chat_server_name      VARCHAR(255),
  chat_server_port      INTEGER,
  PRIMARY KEY (chat_server_id)
);

CREATE TABLE chat_user (
  chat_user_id           BIGINT generated BY DEFAULT AS IDENTITY (START WITH 1),
  chat_user_display_name VARCHAR(255),
  chat_user_nick_name    VARCHAR(255),
  PRIMARY KEY (chat_user_id)
);

CREATE TABLE chat_user_config (
  chat_user_id BIGINT generated BY DEFAULT AS IDENTITY (START WITH 1),
  PRIMARY KEY (chat_user_id)
);

CREATE TABLE todo (
  todo_id    BIGINT generated BY DEFAULT AS IDENTITY (START WITH 1),
  created_at TIMESTAMP,
  finished   BOOLEAN NOT NULL,
  todo_title VARCHAR(255),
  version    BIGINT,
  PRIMARY KEY (todo_id)
);