create table chat_channel (
  chat_channel_name varchar(255) not null,
  chat_channel_hashed_password varchar(255),
  visible boolean not null,
  primary key (chat_channel_name)
);

create table chat_user (
  chat_user_id bigint generated by default as identity,
  chat_user_display_name varchar(255),
  chat_user_nick_name varchar(255),
  primary key (chat_user_id)
);

create table chat_user_config (
  chat_user_id bigint generated by default as identity,
  primary key (chat_user_id)
);

create table todo (
  todo_id bigint generated by default as identity,
  created_at timestamp,
  finished boolean not null,
  todo_title varchar(255),
  version bigint,
  primary key (todo_id)
);